services:
  postgres:
    image: postgres:17-alpine
    container_name: formEngine-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    restart: on-failure
    networks:
      - app_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  drizzle-gate:
    image: ghcr.io/drizzle-team/gateway:latest
    container_name: formEngine-drizzle-gateway
    environment:
      DATABASE_URL: postgresql://postgres:1234@postgres:5432/postgres
      STORE_PATH: /app
    restart: on-failure
    depends_on:
      - postgres
    ports:
      - "4983:4983"
    volumes:
      - drizzle_gateway_data:/app
    networks:
      - app_network

volumes:
  postgres_data:
  drizzle_gateway_data:

networks:
  app_network:
